name: CI

on:
  workflow_run:
    workflows: ["MAKE"]
    types: 
      - completed

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ontology_qc:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.6

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Run ontology QC checks
        env:
          DEFAULT_BRANCH: main
        shell: bash
        run: |
          set -euo pipefail
          cd src/ontology
          make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G'

      - name: Distribute ontology files to root
        shell: bash
        run: |
          set -euo pipefail
          cp src/ontology/wcso-full.* .
          cp src/ontology/wcso-base.* .
          cp src/ontology/wcso-simple.* .

          cp src/ontology/wcso-full.owl wcso.owl
          cp src/ontology/wcso-full.ttl wcso.ttl

      - name: Commit distributed ontology files
        uses: EndBug/add-and-commit@v9
        with:
          message: "distribute ontology files to root"
          default_author: github_actions
          add: "*.owl *.ttl wcso.owl wcso.ttl --force"
          cwd: "."